# Generated by Django 4.2.7 on 2025-11-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('plano_ativo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'cliente_contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContaAPagar',
            fields=[
                ('id_conta_pagar', models.AutoField(primary_key=True, serialize=False)),
                ('home_beneficiada', models.CharField(blank=True, max_length=100, null=True)),
                ('data_vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pendente', max_length=50)),
            ],
            options={
                'db_table': 'conta_a_pagar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContaAReceber',
            fields=[
                ('id_conta_receber', models.AutoField(primary_key=True, serialize=False)),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pendente', max_length=50)),
            ],
            options={
                'db_table': 'conta_a_receber',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Ativo', max_length=50)),
            ],
            options={
                'db_table': 'contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id_financeiro', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('Receita', 'Receita'), ('Despesa', 'Despesa')], max_length=50)),
            ],
            options={
                'db_table': 'financeiro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id_lead', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('origem', models.CharField(blank=True, max_length=50, null=True)),
                ('status_funil', models.CharField(blank=True, max_length=50, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
            ],
            options={
                'db_table': 'leads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id_projeto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_projeto', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Em andamento', max_length=50)),
            ],
            options={
                'db_table': 'projeto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suporte',
            fields=[
                ('id_chamado', models.AutoField(primary_key=True, serialize=False)),
                ('nome_pedido', models.CharField(max_length=100)),
                ('responsavel_solicitacao', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'suporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id_tarefas', models.AutoField(primary_key=True, serialize=False)),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Pendente', max_length=50)),
                ('prioridade', models.CharField(blank=True, choices=[('Baixa', 'Baixa'), ('Média', 'Média'), ('Alta', 'Alta')], max_length=20, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tarefas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('perfil', models.CharField(choices=[('admin', 'Administrador'), ('normal', 'Usuário Normal')], default='normal', max_length=20)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'usuario_projeto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'usuario_tarefa',
                'managed': False,
            },
        ),
    ]
